export const helpOption = '-h, --help'
export const idOption = '-i, --id <id>'
export const queryOption = '-q, --query <query>'
export const bodyOption = '-b, --body <body>'
export const headerOption = '-h, --header <header>'
